##Problems on Numpy

In [ ]:
import numpy as np

Write a NumPy program to compute the multiplication of two given matrixes. 

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7]) 
print(np.dot(mat1, mat2))

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


Write a NumPy program to compute the outer product of two given vectors.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7])
print(np.outer(mat1, mat2))

[[  3   4   6   5   6   7   6  56   7]
 [ 18  24  36  30  36  42  36 336  42]
 [ 15  20  30  25  30  35  30 280  35]
 [  9  12  18  15  18  21  18 168  21]
 [ 12  16  24  20  24  28  24 224  28]
 [ 24  32  48  40  48  56  48 448  56]
 [  6   8  12  10  12  14  12 112  14]
 [ 36  48  72  60  72  84  72 672  84]
 [  9  12  18  15  18  21  18 168  21]]


Write a NumPy program to compute the cross product of two given vectors.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7])
print(np.cross(mat1, mat2))

[[ 16   9 -14]
 [-20  19  -2]
 [-84   4  40]]


Write a NumPy program to compute the determinant of a given square array.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.det(mat1))

98.00000000000004


Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7])
print(np.einsum("mk,kn", mat1, mat2))

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.

In [ ]:
mat1 = ([1, 6, 5]) 
mat2 = ([3, 4, 6])
print(np.inner(mat1, mat2))

57


In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7])
print(np.inner(mat1, mat2))

[[ 57  76 377]
 [ 73  95 298]
 [ 72 103 705]]


Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
w, v = np.linalg.eig(mat1)
print('Eigen values:', w)
print('Eigen vectors:', v)

Eigen values: [15.2876222  -1.02332555 -6.26429664]
Eigen vectors: [[ 0.4759332   0.94493063 -0.04665095]
 [ 0.58923536 -0.04899885 -0.60555074]
 [ 0.65290832 -0.32358184  0.79443816]]


Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6, 56, 7])
print(np.kron(mat1, mat2))

[[  3   4   6  18  24  36  15  20  30]
 [  5   6   7  30  36  42  25  30  35]
 [  6  56   7  36 336  42  30 280  35]
 [  9  12  18  12  16  24  24  32  48]
 [ 15  18  21  20  24  28  40  48  56]
 [ 18 168  21  24 224  28  48 448  56]
 [  6   8  12  36  48  72   9  12  18]
 [ 10  12  14  60  72  84  15  18  21]
 [ 12 112  14  72 672  84  18 168  21]]


Write a NumPy program to compute the condition number of a given matrix.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.cond(mat1))

17.078964945002536


Write a NumPy program to find a matrix or vector norm.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.norm(mat1))

17.549928774784245


Write a NumPy program to compute the determinant of an array.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.det(mat1))

98.00000000000004


Write a NumPy program to compute the inverse of a given matrix.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.inv(mat1))

[[-0.85714286  0.42857143  0.28571429]
 [ 0.07142857 -0.07142857  0.07142857]
 [ 0.28571429  0.         -0.14285714]]


Write a NumPy program to calculate the QR decomposition of a given matrix.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.qr(mat1))

(array([[-2.67261242e-01,  3.58568583e-01, -8.94427191e-01],
       [-8.01783726e-01, -5.97614305e-01, -1.11022302e-16],
       [-5.34522484e-01,  7.17137166e-01,  4.47213595e-01]]), array([[ -3.74165739, -11.22497216,  -9.35414347],
       [  0.        ,   8.36660027,  -0.83666003],
       [  0.        ,   0.        ,  -3.13049517]]))


Write a NumPy program to compute the condition number of a given matrix.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.linalg.cond(mat1))

17.078964945002536


Write a NumPy program to compute the sum of the diagonal element of a given array.

In [ ]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
print(np.trace(mat1))

8
